# Generated by Django 5.0.6 on 2024-06-26 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='service_id',
            new_name='client_id',
        ),
    ]
